language: php

php:
  - 7.2
  - 7.3

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source
  - cp .env.ci .env
  - php artisan migrate
  - php artisan db:seed
  - php artisan key:generate

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
